version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: fxuser
      POSTGRES_PASSWORD: fxpass
      POSTGRES_DB: fx_deals
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fxuser -d fx_deals"]
      interval: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      JDBC_URL: jdbc:postgresql://db:5432/fx_deals
      DB_USER: fxuser
      DB_PASS: fxpass
    volumes:
      - ./sample-data:/app/sample-data
    command: ["java","-jar","/app/app.jar","/app/sample-data/deals-sample.csv"]
    # Alternatively you can run the jar locally via Makefile target

volumes:
  db-data:
