version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fx-db
    environment:
      POSTGRES_USER: fxuser
      POSTGRES_PASSWORD: fxpass
      POSTGRES_DB: fxdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/

  app:
    build: .
    container_name: fx-app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: fxdb
      DB_USER: fxuser
      DB_PASS: fxpass
    volumes:
    - ./sample-data:/app/sample-data
    - ./scripts/wait-for-it.sh:/wait-for-it.sh
    command: ["/wait-for-it.sh", "db:5432", "--", "/app/bin/app", "/app/sample-data/deals-sample.csv"]

volumes:
  pgdata:
