/*
 * This source file was generated by the Gradle 'init' task
 */
package fx.wh;

import fx.wh.database.PostgresClient;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        PostgresClient client = new PostgresClient();
        client.testConnection();
    }
}
